// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PhanMemKeToan.Infrastructure.Persistence;

#nullable disable

namespace PhanMemKeToan.Infrastructure.Persistence.Migrations.Master
{
    [DbContext(typeof(MasterDbContext))]
    partial class MasterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.MasterUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_count");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_sys_master_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_sys_master_users_email");

                    b.ToTable("sys_master_users", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.MasterUserTenant", b =>
                {
                    b.Property<Guid>("MasterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("master_user_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("DisplayRole")
                        .HasColumnType("text")
                        .HasColumnName("display_role");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.HasKey("MasterUserId", "TenantId")
                        .HasName("pk_sys_master_user_tenants");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_sys_master_user_tenants_tenant_id");

                    b.ToTable("sys_master_user_tenants", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TokenFamily")
                        .HasColumnType("uuid")
                        .HasColumnName("token_family");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sys_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_sys_refresh_tokens_token_hash");

                    b.HasIndex("TokenFamily", "IsRevoked")
                        .HasDatabaseName("ix_sys_refresh_tokens_token_family_is_revoked");

                    b.HasIndex("UserId", "TenantId", "IsRevoked")
                        .HasDatabaseName("ix_sys_refresh_tokens_user_tenant");

                    b.ToTable("sys_refresh_tokens", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CloudflareSubdomain")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cloudflare_subdomain");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("ConnectionStringEncrypted")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("connection_string_encrypted");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DatabaseMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("CloudManaged")
                        .HasColumnName("database_mode");

                    b.Property<string>("DatabaseSchemaName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("database_schema_name");

                    b.Property<string>("DbHost")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("db_host");

                    b.Property<string>("DbStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Online")
                        .HasColumnName("db_status");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_sys_tenants");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_sys_tenants_code");

                    b.ToTable("sys_tenants", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.MasterUserTenant", b =>
                {
                    b.HasOne("PhanMemKeToan.Domain.Entities.MasterUser", "MasterUser")
                        .WithMany("MasterUserTenants")
                        .HasForeignKey("MasterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sys_master_user_tenants_sys_master_users_master_user_id");

                    b.HasOne("PhanMemKeToan.Domain.Entities.Tenant", "Tenant")
                        .WithMany("MasterUserTenants")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sys_master_user_tenants_tenants_tenant_id");

                    b.Navigation("MasterUser");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("PhanMemKeToan.Domain.Entities.MasterUser", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sys_refresh_tokens_sys_master_users_user_id");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.MasterUser", b =>
                {
                    b.Navigation("MasterUserTenants");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("MasterUserTenants");
                });
#pragma warning restore 612, 618
        }
    }
}
