// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PhanMemKeToan.Infrastructure.Persistence;

#nullable disable

namespace PhanMemKeToan.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccountCategoryKind")
                        .HasColumnType("integer")
                        .HasColumnName("account_category_kind");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("account_name");

                    b.Property<string>("AccountNameEnglish")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("account_name_english");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("account_number");

                    b.Property<int>("AccountObjectType")
                        .HasColumnType("integer")
                        .HasColumnName("account_object_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("DetailByAccountObject")
                        .HasColumnType("boolean")
                        .HasColumnName("detail_by_account_object");

                    b.Property<bool>("DetailByBankAccount")
                        .HasColumnType("boolean")
                        .HasColumnName("detail_by_bank_account");

                    b.Property<bool>("DetailByContract")
                        .HasColumnType("boolean")
                        .HasColumnName("detail_by_contract");

                    b.Property<bool>("DetailByDepartment")
                        .HasColumnType("boolean")
                        .HasColumnName("detail_by_department");

                    b.Property<bool>("DetailByExpenseItem")
                        .HasColumnType("boolean")
                        .HasColumnName("detail_by_expense_item");

                    b.Property<bool>("DetailByJob")
                        .HasColumnType("boolean")
                        .HasColumnName("detail_by_job");

                    b.Property<bool>("DetailByListItem")
                        .HasColumnType("boolean")
                        .HasColumnName("detail_by_list_item");

                    b.Property<bool>("DetailByOrder")
                        .HasColumnType("boolean")
                        .HasColumnName("detail_by_order");

                    b.Property<bool>("DetailByPUContract")
                        .HasColumnType("boolean")
                        .HasColumnName("detail_by_pu_contract");

                    b.Property<bool>("DetailByProjectWork")
                        .HasColumnType("boolean")
                        .HasColumnName("detail_by_project_work");

                    b.Property<int>("Grade")
                        .HasColumnType("integer")
                        .HasColumnName("grade");

                    b.Property<bool>("Inactive")
                        .HasColumnType("boolean")
                        .HasColumnName("inactive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsParent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_parent");

                    b.Property<bool>("IsPostableInForeignCurrency")
                        .HasColumnType("boolean")
                        .HasColumnName("is_postable_in_foreign_currency");

                    b.Property<string>("MISACodeID")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("misa_code_id");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<Guid?>("ParentID")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("AccountNumber")
                        .HasDatabaseName("IX_Accounts_AccountNumber_Pattern");

                    b.HasIndex("ParentID")
                        .HasDatabaseName("IX_Accounts_ParentID");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Accounts_TenantId");

                    b.HasIndex("TenantId", "AccountNumber")
                        .IsUnique()
                        .HasDatabaseName("UIX_Accounts_TenantId_AccountNumber")
                        .HasFilter("is_deleted = false");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.AccountObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccountObjectGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_object_group_id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_person");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<decimal>("CreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("credit_limit");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Fax")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fax");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("ObjectCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("object_code");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("object_name");

                    b.Property<string>("ObjectNameEnglish")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("object_name_english");

                    b.Property<int>("ObjectType")
                        .HasColumnType("integer")
                        .HasColumnName("object_type");

                    b.Property<int>("PaymentTermDays")
                        .HasColumnType("integer")
                        .HasColumnName("payment_term_days");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tax_code");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_account_objects");

                    b.HasIndex("AccountObjectGroupId")
                        .HasDatabaseName("ix_account_objects_account_object_group_id");

                    b.HasIndex("ObjectType")
                        .HasDatabaseName("IX_AccountObjects_ObjectType");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_AccountObjects_TenantId");

                    b.HasIndex("TenantId", "ObjectCode")
                        .IsUnique()
                        .HasDatabaseName("UIX_AccountObjects_TenantId_ObjectCode")
                        .HasFilter("is_deleted = false");

                    b.ToTable("AccountObjects", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.AccountObjectBankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("account_number");

                    b.Property<Guid>("AccountObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_object_id");

                    b.Property<string>("BankBranch")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("bank_branch");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("bank_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("SwiftCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("swift_code");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_account_object_bank_accounts");

                    b.HasIndex("AccountObjectId")
                        .HasDatabaseName("IX_AccountObjectBankAccounts_AccountObjectId");

                    b.ToTable("AccountObjectBankAccounts", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.AccountObjectEmployeeProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_object_id");

                    b.Property<string>("CitizenId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("citizen_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<int>("DependentCount")
                        .HasColumnType("integer")
                        .HasColumnName("dependent_count");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hire_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("SocialInsuranceNumber")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("social_insurance_number");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_account_object_employee_profiles");

                    b.HasIndex("AccountObjectId")
                        .IsUnique()
                        .HasDatabaseName("UIX_AccountObjectEmployeeProfiles_AccountObjectId");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_account_object_employee_profiles_department_id");

                    b.HasIndex("TenantId", "CitizenId")
                        .IsUnique()
                        .HasDatabaseName("UIX_AccountObjectEmployeeProfiles_TenantId_CitizenId")
                        .HasFilter("citizen_id IS NOT NULL AND is_deleted = false");

                    b.HasIndex("TenantId", "SocialInsuranceNumber")
                        .IsUnique()
                        .HasDatabaseName("UIX_AccountObjectEmployeeProfiles_TenantId_SIN")
                        .HasFilter("social_insurance_number IS NOT NULL AND is_deleted = false");

                    b.ToTable("AccountObjectEmployeeProfiles", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.AccountObjectGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("group_code");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("group_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<int>("ObjectType")
                        .HasColumnType("integer")
                        .HasColumnName("object_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_account_object_groups");

                    b.HasIndex("TenantId", "GroupCode")
                        .IsUnique()
                        .HasDatabaseName("UIX_AccountObjectGroups_TenantId_GroupCode")
                        .HasFilter("is_deleted = false");

                    b.ToTable("AccountObjectGroups", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.AccountObjectOpeningBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_object_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<decimal>("CreditAmount")
                        .HasPrecision(18)
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("credit_amount");

                    b.Property<decimal>("CreditAmountOC")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("credit_amount_oc");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("currency_id");

                    b.Property<decimal>("DebitAmount")
                        .HasPrecision(18)
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("debit_amount");

                    b.Property<decimal>("DebitAmountOC")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("debit_amount_oc");

                    b.Property<decimal>("ExchangeRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("exchange_rate");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_account_object_opening_balances");

                    b.HasIndex("AccountObjectId")
                        .HasDatabaseName("ix_account_object_opening_balances_account_object_id");

                    b.HasIndex("CurrencyId")
                        .HasDatabaseName("ix_account_object_opening_balances_currency_id");

                    b.HasIndex("TenantId", "AccountObjectId", "CurrencyId")
                        .IsUnique()
                        .HasDatabaseName("UIX_AccountObjectOpeningBalances_TenantId_ObjectId_CurrencyId")
                        .HasFilter("is_deleted = false");

                    b.ToTable("AccountObjectOpeningBalances", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency_code");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("currency_name");

                    b.Property<string>("CurrencyNameEnglish")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("currency_name_english");

                    b.Property<decimal>("ExchangeRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("exchange_rate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("symbol");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_currencies");

                    b.HasIndex("TenantId", "CurrencyCode")
                        .IsUnique()
                        .HasDatabaseName("UIX_Currencies_TenantId_CurrencyCode")
                        .HasFilter("is_deleted = false");

                    b.ToTable("Currencies", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("department_code");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("department_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_departments_parent_id");

                    b.HasIndex("TenantId", "DepartmentCode")
                        .IsUnique()
                        .HasDatabaseName("UIX_Departments_TenantId_DepartmentCode")
                        .HasFilter("is_deleted = false");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.ExpenseItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("ExpenseCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("expense_code");

                    b.Property<string>("ExpenseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("expense_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_expense_items");

                    b.HasIndex("TenantId", "ExpenseCode")
                        .IsUnique()
                        .HasDatabaseName("UIX_ExpenseItems_TenantId_ExpenseCode")
                        .HasFilter("is_deleted = false");

                    b.ToTable("ExpenseItems", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("barcode");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<int>("CostingMethod")
                        .HasColumnType("integer")
                        .HasColumnName("costing_method");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<decimal?>("DefaultTaxRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("default_tax_rate");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("FormulaTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("formula_template_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsFollowExpiry")
                        .HasColumnType("boolean")
                        .HasColumnName("is_follow_expiry");

                    b.Property<bool>("IsFollowLot")
                        .HasColumnType("boolean")
                        .HasColumnName("is_follow_lot");

                    b.Property<bool>("IsFollowSerial")
                        .HasColumnType("boolean")
                        .HasColumnName("is_follow_serial");

                    b.Property<bool>("IsPanelItem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_panel_item");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("item_code");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("item_name");

                    b.Property<string>("ItemNameEnglish")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("item_name_english");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer")
                        .HasColumnName("item_type");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("integer")
                        .HasColumnName("lead_time_days");

                    b.Property<decimal>("MaxStockLevel")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("max_stock_level");

                    b.Property<decimal>("MinStockLevel")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("min_stock_level");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<Guid?>("PanelUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("panel_unit_id");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<decimal?>("SalePrice1")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("sale_price1");

                    b.Property<decimal?>("SalePrice2")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("sale_price2");

                    b.Property<decimal?>("SalePrice3")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("sale_price3");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_inventory_items");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_inventory_items_category_id");

                    b.HasIndex("FormulaTemplateId")
                        .HasDatabaseName("ix_inventory_items_formula_template_id");

                    b.HasIndex("ItemType")
                        .HasDatabaseName("IX_InventoryItems_ItemType");

                    b.HasIndex("PanelUnitId")
                        .HasDatabaseName("ix_inventory_items_panel_unit_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_InventoryItems_TenantId");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_inventory_items_unit_id");

                    b.HasIndex("TenantId", "ItemCode")
                        .IsUnique()
                        .HasDatabaseName("UIX_InventoryItems_TenantId_ItemCode")
                        .HasFilter("is_deleted = false");

                    b.ToTable("InventoryItems", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.InventoryItemAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttributeTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_type_id");

                    b.Property<string>("AttributeValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("attribute_value");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_item_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_item_attributes");

                    b.HasIndex("AttributeTypeId")
                        .HasDatabaseName("ix_inventory_item_attributes_attribute_type_id");

                    b.HasIndex("InventoryItemId")
                        .HasDatabaseName("ix_inventory_item_attributes_inventory_item_id");

                    b.HasIndex("TenantId", "InventoryItemId", "AttributeTypeId")
                        .IsUnique()
                        .HasDatabaseName("UIX_InventoryItemAttributes_TenantId_ItemId_AttributeTypeId")
                        .HasFilter("is_deleted = false");

                    b.ToTable("InventoryItemAttributes", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.InventoryItemBarcode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BarcodeType")
                        .HasColumnType("integer")
                        .HasColumnName("barcode_type");

                    b.Property<string>("BarcodeValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("barcode_value");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_item_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_item_barcodes");

                    b.HasIndex("InventoryItemId")
                        .HasDatabaseName("ix_inventory_item_barcodes_inventory_item_id");

                    b.HasIndex("TenantId", "BarcodeValue")
                        .IsUnique()
                        .HasDatabaseName("UIX_InventoryItemBarcodes_TenantId_BarcodeValue")
                        .HasFilter("is_deleted = false");

                    b.ToTable("InventoryItemBarcodes", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.InventoryItemCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("category_code");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("category_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_item_categories");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_inventory_item_categories_parent_id");

                    b.HasIndex("IsActive", "SortOrder")
                        .HasDatabaseName("IX_InventoryItemCategories_IsActive_SortOrder");

                    b.HasIndex("TenantId", "CategoryCode")
                        .IsUnique()
                        .HasDatabaseName("UIX_InventoryItemCategories_TenantId_CategoryCode")
                        .HasFilter("is_deleted = false");

                    b.ToTable("InventoryItemCategories", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.InventoryItemOpeningBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18)
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("currency_id");

                    b.Property<decimal>("ExchangeRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("exchange_rate");

                    b.Property<decimal?>("ForeignAmount")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("foreign_amount");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_item_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_cost");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_item_opening_balances");

                    b.HasIndex("CurrencyId")
                        .HasDatabaseName("ix_inventory_item_opening_balances_currency_id");

                    b.HasIndex("InventoryItemId")
                        .HasDatabaseName("ix_inventory_item_opening_balances_inventory_item_id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_inventory_item_opening_balances_unit_id");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("ix_inventory_item_opening_balances_warehouse_id");

                    b.HasIndex("TenantId", "InventoryItemId", "WarehouseId", "UnitId")
                        .IsUnique()
                        .HasDatabaseName("UIX_InventoryItemOpeningBalances_TenantId_ItemId_WarehouseId_UnitId")
                        .HasFilter("is_deleted = false");

                    b.ToTable("InventoryItemOpeningBalances", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.InventoryItemUnitConvert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("ConvertRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("convert_rate");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_item_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_item_unit_converts");

                    b.HasIndex("InventoryItemId")
                        .HasDatabaseName("ix_inventory_item_unit_converts_inventory_item_id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_inventory_item_unit_converts_unit_id");

                    b.HasIndex("TenantId", "InventoryItemId", "UnitId")
                        .IsUnique()
                        .HasDatabaseName("UIX_InventoryItemUnitConverts_TenantId_ItemId_UnitId")
                        .HasFilter("is_deleted = false");

                    b.ToTable("InventoryItemUnitConverts", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.InventoryQuantityFormulaDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid>("FormulaTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("formula_template_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("MaterialItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_item_id");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_quantity_formula_details");

                    b.HasIndex("FormulaTemplateId")
                        .HasDatabaseName("ix_inventory_quantity_formula_details_formula_template_id");

                    b.HasIndex("MaterialItemId")
                        .HasDatabaseName("ix_inventory_quantity_formula_details_material_item_id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_inventory_quantity_formula_details_unit_id");

                    b.ToTable("InventoryQuantityFormulaDetails", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.InventoryQuantityFormulaTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("TemplateCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("template_code");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("template_name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_quantity_formula_templates");

                    b.HasIndex("TenantId", "TemplateCode")
                        .IsUnique()
                        .HasDatabaseName("UIX_InventoryQuantityFormulaTemplates_TenantId_TemplateCode")
                        .HasFilter("is_deleted = false");

                    b.ToTable("InventoryQuantityFormulaTemplates", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.ItemAttributeType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttributeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("attribute_code");

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("attribute_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_item_attribute_types");

                    b.HasIndex("TenantId", "AttributeCode")
                        .IsUnique()
                        .HasDatabaseName("UIX_ItemAttributeTypes_TenantId_AttributeCode")
                        .HasFilter("is_deleted = false");

                    b.ToTable("ItemAttributeTypes", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("ModuleCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("module_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_sys_permissions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_sys_permissions_code");

                    b.HasIndex("ModuleCode")
                        .HasDatabaseName("ix_sys_permissions_module_code");

                    b.ToTable("sys_permissions", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TokenFamily")
                        .HasColumnType("uuid")
                        .HasColumnName("token_family");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sys_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_sys_refresh_tokens_token_hash");

                    b.HasIndex("TokenFamily", "IsRevoked")
                        .HasDatabaseName("ix_sys_refresh_tokens_token_family_is_revoked");

                    b.HasIndex("UserId", "TenantId", "IsRevoked")
                        .HasDatabaseName("ix_sys_refresh_tokens_user_tenant");

                    b.ToTable("sys_refresh_tokens", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_sys_roles");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_sys_roles_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_sys_roles_tenant_id_name");

                    b.ToTable("sys_roles", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_sys_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_sys_role_permissions_permission_id");

                    b.ToTable("sys_role_permissions", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CloudflareSubdomain")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cloudflare_subdomain");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("ConnectionStringEncrypted")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("connection_string_encrypted");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DatabaseMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("CloudManaged")
                        .HasColumnName("database_mode");

                    b.Property<string>("DatabaseSchemaName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("database_schema_name");

                    b.Property<string>("DbHost")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("db_host");

                    b.Property<string>("DbStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Online")
                        .HasColumnName("db_status");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_sys_tenants");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_sys_tenants_code");

                    b.ToTable("sys_tenants", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("unit_code");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("unit_name");

                    b.HasKey("Id")
                        .HasName("pk_units");

                    b.HasIndex("TenantId", "UnitCode")
                        .IsUnique()
                        .HasDatabaseName("UIX_Units_TenantId_UnitCode")
                        .HasFilter("is_deleted = false");

                    b.ToTable("Units", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_count");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_sys_users");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_sys_users_tenant_id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_sys_users_tenant_id_email");

                    b.ToTable("sys_users", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_sys_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_sys_user_roles_role_id");

                    b.ToTable("sys_user_roles", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("WarehouseCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("warehouse_code");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("warehouse_name");

                    b.HasKey("Id")
                        .HasName("pk_warehouses");

                    b.HasIndex("TenantId", "WarehouseCode")
                        .IsUnique()
                        .HasDatabaseName("UIX_Warehouses_TenantId_WarehouseCode")
                        .HasFilter("is_deleted = false");

                    b.ToTable("Warehouses", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.Account", b =>
                {
                    b.HasOne("PhanMemKeToan.Domain.Entities.Account", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_accounts_accounts_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.AccountObject", b =>
                {
                    b.HasOne("PhanMemKeToan.Domain.Entities.AccountObjectGroup", "AccountObjectGroup")
                        .WithMany("AccountObjects")
                        .HasForeignKey("AccountObjectGroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_account_objects_account_object_groups_account_object_group_id");

                    b.Navigation("AccountObjectGroup");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.AccountObjectBankAccount", b =>
                {
                    b.HasOne("PhanMemKeToan.Domain.Entities.AccountObject", "AccountObject")
                        .WithMany("BankAccounts")
                        .HasForeignKey("AccountObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_object_bank_accounts_account_objects_account_object_id");

                    b.Navigation("AccountObject");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.AccountObjectEmployeeProfile", b =>
                {
                    b.HasOne("PhanMemKeToan.Domain.Entities.AccountObject", "AccountObject")
                        .WithOne("EmployeeProfile")
                        .HasForeignKey("PhanMemKeToan.Domain.Entities.AccountObjectEmployeeProfile", "AccountObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_object_employee_profiles_account_objects_account_object");

                    b.HasOne("PhanMemKeToan.Domain.Entities.Department", "Department")
                        .WithMany("EmployeeProfiles")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_account_object_employee_profiles_departments_department_id");

                    b.Navigation("AccountObject");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.AccountObjectOpeningBalance", b =>
                {
                    b.HasOne("PhanMemKeToan.Domain.Entities.AccountObject", "AccountObject")
                        .WithMany("OpeningBalances")
                        .HasForeignKey("AccountObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_object_opening_balances_account_objects_account_object_");

                    b.HasOne("PhanMemKeToan.Domain.Entities.Currency", "Currency")
                        .WithMany("OpeningBalances")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_account_object_opening_balances_currencies_currency_id");

                    b.Navigation("AccountObject");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.Department", b =>
                {
                    b.HasOne("PhanMemKeToan.Domain.Entities.Department", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_departments_departments_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.InventoryItem", b =>
                {
                    b.HasOne("PhanMemKeToan.Domain.Entities.InventoryItemCategory", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_inventory_items_inventory_item_categories_category_id");

                    b.HasOne("PhanMemKeToan.Domain.Entities.InventoryQuantityFormulaTemplate", "FormulaTemplate")
                        .WithMany("Items")
                        .HasForeignKey("FormulaTemplateId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_inventory_items_inventory_quantity_formula_templates_formula");

                    b.HasOne("PhanMemKeToan.Domain.Entities.Unit", "PanelUnit")
                        .WithMany()
                        .HasForeignKey("PanelUnitId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_inventory_items_units_panel_unit_id");

                    b.HasOne("PhanMemKeToan.Domain.Entities.Unit", "Unit")
                        .WithMany("Items")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_items_units_unit_id");

                    b.Navigation("Category");

                    b.Navigation("FormulaTemplate");

                    b.Navigation("PanelUnit");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.InventoryItemAttribute", b =>
                {
                    b.HasOne("PhanMemKeToan.Domain.Entities.ItemAttributeType", "AttributeType")
                        .WithMany("ItemAttributes")
                        .HasForeignKey("AttributeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_item_attributes_item_attribute_types_attribute_type");

                    b.HasOne("PhanMemKeToan.Domain.Entities.InventoryItem", "InventoryItem")
                        .WithMany("ItemAttributes")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_item_attributes_inventory_items_inventory_item_id");

                    b.Navigation("AttributeType");

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.InventoryItemBarcode", b =>
                {
                    b.HasOne("PhanMemKeToan.Domain.Entities.InventoryItem", "InventoryItem")
                        .WithMany("Barcodes")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_item_barcodes_inventory_items_inventory_item_id");

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.InventoryItemCategory", b =>
                {
                    b.HasOne("PhanMemKeToan.Domain.Entities.InventoryItemCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_item_categories_inventory_item_categories_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.InventoryItemOpeningBalance", b =>
                {
                    b.HasOne("PhanMemKeToan.Domain.Entities.Currency", "Currency")
                        .WithMany("InventoryOpeningBalances")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_item_opening_balances_currencies_currency_id");

                    b.HasOne("PhanMemKeToan.Domain.Entities.InventoryItem", "InventoryItem")
                        .WithMany("OpeningBalances")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_item_opening_balances_inventory_items_inventory_item_");

                    b.HasOne("PhanMemKeToan.Domain.Entities.Unit", "Unit")
                        .WithMany("OpeningBalances")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_item_opening_balances_units_unit_id");

                    b.HasOne("PhanMemKeToan.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("OpeningBalances")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_item_opening_balances_warehouses_warehouse_id");

                    b.Navigation("Currency");

                    b.Navigation("InventoryItem");

                    b.Navigation("Unit");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.InventoryItemUnitConvert", b =>
                {
                    b.HasOne("PhanMemKeToan.Domain.Entities.InventoryItem", "InventoryItem")
                        .WithMany("UnitConverts")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_item_unit_converts_inventory_items_inventory_item_id");

                    b.HasOne("PhanMemKeToan.Domain.Entities.Unit", "Unit")
                        .WithMany("UnitConverts")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_item_unit_converts_units_unit_id");

                    b.Navigation("InventoryItem");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.InventoryQuantityFormulaDetail", b =>
                {
                    b.HasOne("PhanMemKeToan.Domain.Entities.InventoryQuantityFormulaTemplate", "FormulaTemplate")
                        .WithMany("Details")
                        .HasForeignKey("FormulaTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_quantity_formula_details_inventory_quantity_formula_");

                    b.HasOne("PhanMemKeToan.Domain.Entities.InventoryItem", "MaterialItem")
                        .WithMany()
                        .HasForeignKey("MaterialItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_quantity_formula_details_inventory_items_material_ite");

                    b.HasOne("PhanMemKeToan.Domain.Entities.Unit", "Unit")
                        .WithMany("FormulaDetails")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_quantity_formula_details_units_unit_id");

                    b.Navigation("FormulaTemplate");

                    b.Navigation("MaterialItem");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("PhanMemKeToan.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sys_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("PhanMemKeToan.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sys_role_permissions_sys_permissions_permission_id");

                    b.HasOne("PhanMemKeToan.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sys_role_permissions_sys_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("PhanMemKeToan.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sys_user_roles_sys_roles_role_id");

                    b.HasOne("PhanMemKeToan.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sys_user_roles_sys_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.Account", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.AccountObject", b =>
                {
                    b.Navigation("BankAccounts");

                    b.Navigation("EmployeeProfile");

                    b.Navigation("OpeningBalances");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.AccountObjectGroup", b =>
                {
                    b.Navigation("AccountObjects");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.Currency", b =>
                {
                    b.Navigation("InventoryOpeningBalances");

                    b.Navigation("OpeningBalances");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.Department", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("EmployeeProfiles");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.InventoryItem", b =>
                {
                    b.Navigation("Barcodes");

                    b.Navigation("ItemAttributes");

                    b.Navigation("OpeningBalances");

                    b.Navigation("UnitConverts");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.InventoryItemCategory", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.InventoryQuantityFormulaTemplate", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.ItemAttributeType", b =>
                {
                    b.Navigation("ItemAttributes");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.Unit", b =>
                {
                    b.Navigation("FormulaDetails");

                    b.Navigation("Items");

                    b.Navigation("OpeningBalances");

                    b.Navigation("UnitConverts");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.Warehouse", b =>
                {
                    b.Navigation("OpeningBalances");
                });
#pragma warning restore 612, 618
        }
    }
}
