// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PhanMemKeToan.Infrastructure.Persistence;

#nullable disable

namespace PhanMemKeToan.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccountCategoryKind")
                        .HasColumnType("integer")
                        .HasColumnName("account_category_kind");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("account_name");

                    b.Property<string>("AccountNameEnglish")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("account_name_english");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("account_number");

                    b.Property<int>("AccountObjectType")
                        .HasColumnType("integer")
                        .HasColumnName("account_object_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("DetailByAccountObject")
                        .HasColumnType("boolean")
                        .HasColumnName("detail_by_account_object");

                    b.Property<bool>("DetailByBankAccount")
                        .HasColumnType("boolean")
                        .HasColumnName("detail_by_bank_account");

                    b.Property<bool>("DetailByContract")
                        .HasColumnType("boolean")
                        .HasColumnName("detail_by_contract");

                    b.Property<bool>("DetailByDepartment")
                        .HasColumnType("boolean")
                        .HasColumnName("detail_by_department");

                    b.Property<bool>("DetailByExpenseItem")
                        .HasColumnType("boolean")
                        .HasColumnName("detail_by_expense_item");

                    b.Property<bool>("DetailByJob")
                        .HasColumnType("boolean")
                        .HasColumnName("detail_by_job");

                    b.Property<bool>("DetailByListItem")
                        .HasColumnType("boolean")
                        .HasColumnName("detail_by_list_item");

                    b.Property<bool>("DetailByOrder")
                        .HasColumnType("boolean")
                        .HasColumnName("detail_by_order");

                    b.Property<bool>("DetailByPUContract")
                        .HasColumnType("boolean")
                        .HasColumnName("detail_by_pu_contract");

                    b.Property<bool>("DetailByProjectWork")
                        .HasColumnType("boolean")
                        .HasColumnName("detail_by_project_work");

                    b.Property<int>("Grade")
                        .HasColumnType("integer")
                        .HasColumnName("grade");

                    b.Property<bool>("Inactive")
                        .HasColumnType("boolean")
                        .HasColumnName("inactive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsParent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_parent");

                    b.Property<bool>("IsPostableInForeignCurrency")
                        .HasColumnType("boolean")
                        .HasColumnName("is_postable_in_foreign_currency");

                    b.Property<string>("MISACodeID")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("misa_code_id");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<Guid?>("ParentID")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("AccountNumber")
                        .HasDatabaseName("IX_Accounts_AccountNumber_Pattern");

                    b.HasIndex("ParentID")
                        .HasDatabaseName("IX_Accounts_ParentID");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Accounts_TenantId");

                    b.HasIndex("TenantId", "AccountNumber")
                        .IsUnique()
                        .HasDatabaseName("UIX_Accounts_TenantId_AccountNumber")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("ModuleCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("module_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_sys_permissions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_sys_permissions_code");

                    b.HasIndex("ModuleCode")
                        .HasDatabaseName("ix_sys_permissions_module_code");

                    b.ToTable("sys_permissions", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TokenFamily")
                        .HasColumnType("uuid")
                        .HasColumnName("token_family");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sys_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_sys_refresh_tokens_token_hash");

                    b.HasIndex("TokenFamily", "IsRevoked")
                        .HasDatabaseName("ix_sys_refresh_tokens_token_family_is_revoked");

                    b.HasIndex("UserId", "TenantId", "IsRevoked")
                        .HasDatabaseName("ix_sys_refresh_tokens_user_tenant");

                    b.ToTable("sys_refresh_tokens", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_sys_roles");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_sys_roles_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_sys_roles_tenant_id_name");

                    b.ToTable("sys_roles", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_sys_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_sys_role_permissions_permission_id");

                    b.ToTable("sys_role_permissions", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CloudflareSubdomain")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cloudflare_subdomain");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("ConnectionStringEncrypted")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("connection_string_encrypted");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DatabaseMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("CloudManaged")
                        .HasColumnName("database_mode");

                    b.Property<string>("DatabaseSchemaName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("database_schema_name");

                    b.Property<string>("DbHost")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("db_host");

                    b.Property<string>("DbStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Online")
                        .HasColumnName("db_status");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_sys_tenants");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_sys_tenants_code");

                    b.ToTable("sys_tenants", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_count");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_sys_users");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_sys_users_tenant_id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_sys_users_tenant_id_email");

                    b.ToTable("sys_users", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_sys_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_sys_user_roles_role_id");

                    b.ToTable("sys_user_roles", (string)null);
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.Account", b =>
                {
                    b.HasOne("PhanMemKeToan.Domain.Entities.Account", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_accounts_accounts_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("PhanMemKeToan.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sys_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("PhanMemKeToan.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sys_role_permissions_sys_permissions_permission_id");

                    b.HasOne("PhanMemKeToan.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sys_role_permissions_sys_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("PhanMemKeToan.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sys_user_roles_sys_roles_role_id");

                    b.HasOne("PhanMemKeToan.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sys_user_roles_sys_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.Account", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("PhanMemKeToan.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
